export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
export const MEETING_FOUND = 'MEETING_FOUND';
export const USER_JOINED = 'USER_JOINED';
export const MUTE_USER = 'MUTE_USER';
export const USER_NAME_CHANGED = 'USER_NAME_CHANGED';
export const USER_LEFT = 'USER_LEFT';
export const VIDEO_TRACK_ADDED = 'VIDEO_TRACK_ADDED';
export const VIDEO_TRACK_REMOVED = 'VIDEO_TRACK_REMOVED';
export const FOCUSED_USER_CHANGED= 'FOCUSED_USER_CHANGED';
export const ME_USER_CREATED = 'ME_USER_CREATED';
export const MY_CAMERA_MUTED = 'MY_CAMERA_MUTED';
export const USER_CAMERA_MUTE_CHANGED = 'USER_CAMERA_MUTE_CHANGED';
export const SCREEN_SHARE_STARTED = 'SCREEN_SHARE_STARTED';
export const SCREEN_SHARE_STOPPED = 'SCREEN_SHARE_STOPPED';
/* Page events */
export const CHANGE_PAGE = 'CHANGE_PAGE';

/* UI events */
export const PART_LIST_TOGGLED = 'PART_LIST_TOGGLED';